baseURL = 'https://calvernaz.github.io'
languageCode = 'en-us'
title = 'Weirdloop'
theme = 'holy'
copyright = 'weirdloop'

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
